version: 0.2

env:
  variables:
    HOMEPAGE_S3_BUCKET: "www.inoue-kobo.com"

phases:
  install:
    commands:
      - pip install --upgrade pip
      - pip install --upgrade awscli
      - aws --version
      - pip install mkdocs
      - mkdocs --version
      - pip install mkdocs-cinder
      - pip install python-markdown-math
      - pip install mkdocs-macros-plugin
  pre_build:
    commands:
      - pwd
      - find ./
      - perl scripts/get-set-file-times.pl
  build:
    commands:
      - mkdocs build
  post_build:
    commands:
      - cd site
      - pwd
      - echo $HOMEPAGE_S3_BUCKET
      - aws s3 sync . s3://$HOMEPAGE_S3_BUCKET/docs --delete
      - aws cloudfront create-invalidation --region ap-northeast-1 --distribution-id E3JEKHZG9UN3GI --paths "/*"
