version: 0.2

env:
  variables:
    WEBSITE_S3_BUCKET: "www.inoue-kobo.com"

phases:
  install:
    commands:
      - pip install --upgrade pip
      - pip install --upgrade awscli
      - aws --version
      - pip install mkdocs
      - mkdocs --version
      - pip install mkdocs-cinder
      - pip install python-markdown-math
  pre_build:
    commands:
  build:
    commands:
      - mkdocs build
  post_build:
    commands:
      - cd site
      - pwd
      - aws s3 sync . s3://$WEBSITE_S3_BUCKET/public --delete
      - aws cloudfront create-invalidation --region ap-northeast-1 --distribution-id E3JEKHZG9UN3GI --paths "/*"