# web site setting
site_name: INOUE-KOBO.COM
site_url: https://www.inoue-kobo.com/
site_author: hideki@inoue-kobo.com
site_description: フリーランスのシステムアーキテクト、機械学習エンジニアです。 技術メモやポートフォリオを公開しています。
google_analytics: ['UA-24462002-1', 'auto']
copyright: inoue-kobo.com
repo_url: https://github.com/lhideki/www.inoue-kobo.com/
repo_name: GitHub

# navigation
nav:
  - HOME: index.md
  - AWS:
    - MkdocsとS3/Cloudfrontによるドキュメント公開システムの構築: aws/mkdocs-s3-cloudfront/index.md
    - mkdocs\-macrosを利用してサムネイル表示する: aws/mkdocs-macros/index.md
    - AWS SageMaker Ground Truthでテキストのラベリングを試してみる: aws/sagemaker-ground-truth/index.md
    - AWS re:Invent 2018 新機能・新サービス纏め: aws/reinvent-2018-service-summary/index.md
    - SageMakerでTensorFlow+Kerasによる独自モデルをトレーニングする方法: aws/sagemaker-with-mymodel/index.md
    - SageMakerでKerasの独自モデルをトレーニングしてデプロイするまで(Python3対応): aws/sagemaker-with-keras-traing2deploy/index.md
    - AWS DeepLens Tips: aws/deeplens-tips/index.md
    - SageMakerで独自コンテナでトレーニングする方法: aws/sagemaker-with-mycontainer/index.md
    - SageMakerで利用できるDeepChemのためDockerfile: aws/sagemaker-with-deepchem/index.md
    - SageMaker Canvasを使ってみた: aws/sagemaker-canvas/index.md
  - AI/ML:
    - GANでピカチュウを描いてみる: ai_ml/gan-pikachu/index.md
    - GCP AutoML Natural Languageのベンチマーク: ai_ml/automl-benchmark/index.md
    - FizzBuzz問題をニューラルネットワークで解いてみる: ai_ml/fizzbuzz-ml/index.md
    - 各種Tokenize手法に依存したベクトル化手法の比較: ai_ml/comp-vectorizer/index.md
    - Auto-Kerasを使ってみる: ai_ml/auto-keras/index.md
    - Auto-KerasでTextClassifierを使って見る: ai_ml/auto-keras-text/index.md
    - 自然言語ベクトル化用Pythonモジュール(text-vectorian)をリリースしました: ai_ml/text-vectorian/index.md
    - Self-Attentionを利用したテキスト分類: ai_ml/text-classification-by-selfattention/index.md
    - 自然言語処理の分類問題の入力信号に、単語単位の入力だけではなく文字単位の入力を使用する: ai_ml/word-or-character/index.md
    - SentencePiece+word2vecでコーパスによる差を確認してみる: ai_ml/comp-corpus/index.md
    - SentencePiece + 日本語WikipediaのBERTモデルをKeras BERTで利用する: ai_ml/keras-bert/index.md
    - 自然言語処理で使われるAttentionのWeightを可視化する: ai_ml/attention-visualize/index.md
    - Fighting ICEを動かしてみる: ai_ml/fighting-ice/index.md
    - sumyを使って青空文庫を要約してみる: ai_ml/sumy-aozora/index.md
    - Keras BERTでファインチューニングしてみる: ai_ml/keras-bert-with-finetuning/index.md
    - OpenAI Gym API for Fighting ICEを動かしてみる: ai_ml/gym-fightingice/index.md
    - もっと簡単にKeras BERTでファインチューニングしてみる: ai_ml/keras-bert-with-text-vectorian/index.md
    - XGBoostをOptunaでパラメータチューニングする: ai_ml/xgboost-with-optuna/index.md
    - BERTおよびWord2Vecで文の類似性を確認する: ai_ml/sentence-similarity/index.md
    - LightGBMをOptunaでパラメータチューニングする: ai_ml/lightbgm-with-optuna/index.md
    - 自然言語処理で使われるAttentionのWeightを可視化する(spaCy版): ai_ml/attention-visualize-with-spacy/index.md
    - PyCaretで学ぶデータ分析におけるAutoMLの利用: ai_ml/pycaret-basic/index.md
    - Huggingface TransformersでBERTをFine Tuningしてみる: ai_ml/hugging-face/index.md
  - REST API:
    - GitHubにpushする際にQiitaにも投稿する: restapi/qiita_posting/index.md
    - Notionのデータベースに対するViewerをRetoolで作ってみた: restapi/notion-with-retool/index.md
  - WEB SERVICE:
    - AIGAOMOI - 日本語文書感情分析サービス: webservice/aigaomoi/index.md
    - Share My Text - Share your short text in short time: webservice/sharemytext/index.md
    - Notion評価レポート: webservice/notion/index.md
  - ABOUT: about.md

# theme
theme:
  name: 'cinder'
  language: 'ja'
  logo: 'images/log.png'
  favicon: 'images/favicon.ico'
  custom_dir: 'theme'

# plugins
plugins:
  - search
  - macros

# search engin
extra:
  search:
    lang: jp

# extension
markdown_extensions:
  - attr_list
  - footnotes
  - mdx_math
  - meta
  - codehilite:
      guess_lang: false
  - toc:
      permalink: true

## custom js/css
extra_javascript:
  - "js/custom.js"
  - "js/jssocials.min.js"
extra_css:
  - "css/custom.css"

## othters
use_directory_urls: false

dev_addr: '127.0.0.1:8080'