# web site setting
site_name: INOUE-KOBO.COM
site_url: https://www.inoue-kobo.com/
site_author: hideki@inoue-kobo.com
google_analytics: ['UA-24462002-1', 'auto']
copyright: inoue-kobo.com
repo_url: https://github.com/lhideki/www.inoue-kobo.com/
repo_name: GitHub

# navigation
nav:
  - HOME: index.md
  - AWS:
    - MkdocsとS3/Cloudfrontによるドキュメント公開システムの構築: aws/mkdocs-s3-cloudfront/index.md
    - mkdocs\-macrosを利用してサムネイル表示する: aws/mkdocs-macros/index.md
    - AWS SageMaker Ground Truthでテキストのラベリングを試してみる: aws/sagemaker-ground-truth/index.md
    - AWS re:Invent 2018 新機能・新サービス纏め: aws/reinvent-2018-service-summary/index.md
  - AI/ML:
    - GANでピカチュウを描いてみる: ai_ml/gan-pikachu/index.md
    - GCP AutoML Natural Languageのベンチマーク: ai_ml/automl-benchmark/index.md
    - FizzBuzz問題をニューラルネットワークで解いてみる: ai_ml/fizzbuzz-ml/index.md
    - 各種Tokenize手法に依存したベクトル化手法の比較: ai_ml/comp-vectorizer/index.md
    - Auto-Kerasを使ってみる: ai_ml/auto-keras/index.md
    - Auto-KerasでTextClassifierを使って見る: ai_ml/auto-keras-text/index.md
    - 自然言語ベクトル化用Pythonモジュール(text-vectorian)をリリースしました: ai_ml/text-vectorian/index.md
    - SageMakerでTensorFlow+Kerasによる独自モデルをトレーニングする方法: ai_ml/sagemaker-with-mymodel/index.md
  - REST API:
    - GitHubにpushする際にQiitaにも投稿する: restapi/qiita_posting/index.md
  - WEB SERVICE:
    - AIGAOMOI - 日本語文書感情分析サービス: webservice/aigaomoi/index.md
    - Share My Text - Share your short text in short time: webservice/sharemytext/index.md
  - ABOUT: about.md

# theme
theme:
  name: 'cinder'
  language: 'ja'
  logo: 'images/log.png'
  favicon: 'images/favicon.ico'
  custom_dir: 'theme'

# plugins
plugins:
  - search
  - macros

# search engin
extra:
  search:
    lang: jp

# extension
markdown_extensions:
  - attr_list
  - footnotes
  - mdx_math
  - codehilite:
      guess_lang: false
  - toc:
      permalink: true

## custom js/css
extra_javascript:
  - "js/custom.js"
  - "js/jssocials.min.js"
extra_css:
  - "css/custom.css"

## othters
use_directory_urls: false

dev_addr: '127.0.0.1:8080'