# web site setting
site_name: INOUE-KOBO.COM
site_url: https://www.inoue-kobo.com/
site_author: hideki@inoue-kobo.com
google_analytics: ['UA-24462002-1', 'auto']
copyright: inoue-kobo.com
repo_url: https://github.com/lhideki/www.inoue-kobo.com/
repo_name: GitHub

# theme
theme:
  name: 'cinder'
  language: 'ja'
  logo: 'images/favicon.png'
  favicon: 'images/favicon.ico'

# search engin
extra:
  search:
    language: 'jp'

# extension
markdown_extensions:
  - attr_list
  - admonition
  - footnotes
  - mdx_math
  - codehilite:
      guess_lang: false
  - toc:
      permalink: true
