baseURL = "https://www.inoue-kobo.com/"
languageCode = "ja"
title = "INOUE-KOBO.COM"
theme = "mainroad"
pagination.pagerSize = "10"
summaryLength = "5"

[menu]
[[menu.main]]
  identifier = 'home'
  name = 'HOME'
  pre = "<i class='fa fa-heart'></i>"
  url = '/'
  weight = -110

[services.googleAnalytics]
  ID = "G-S8ZWB6Y7EL"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[Params]
  description = "フリーランスのシステムアーキテクト、機械学習エンジニアです。 技術メモやポートフォリオを公開しています。"
  copyright = "www.inoue-kobo.com"
  opengraph = true
  schema = true
  twitter_cards = false
  readmore = true
  authorbox = true
  toc = true
  pager = true
  post_meta = ["author", "date", "categories", "translations"]
  mainSections = ["aws", "ai_ml", "restapi", "webservice", "discord", "llm", "training"]
  dateformat = "2006-01-02"
  mathjax = true
  mathjaxPath = "https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.6/MathJax.js"
  mathjaxConfig = "TeX-AMS-MML_HTMLorMML"
#  googleFontsLink = "https://fonts.googleapis.com/css?family=Open+Sans:400,400i,700"
  googleFontsLink = "https://fonts.googleapis.com/css?family=Noto+Sans+JP&display=swap"
  customCSS = ["css/custom.css"]
  customJS = ["js/custom.js"]

[Params.Author] # Used in authorbox
  name = "Hideki INOUE"
  bio = "フリーランスのシステムアーキテクト、機械学習エンジニアです。 "
  #avatar = "static/images/favicon.ico"

[Params.logo]
  image = "images/computer-2982270_1280.jpg"
  title = "INOUE-KOBO.COM"
  subtitle = "フリーランスのシステムアーキテクト、機械学習エンジニアです。 技術メモやポートフォリオを公開しています。"

[Params.style.vars]
  highlightColor = "#466dc0"
  fontFamilyPrimary = "'Noto Sans JP','Open Sans', Helvetica, Arial, sans-serif"
  fontFamilySecondary = "SFMono-Regular, Menlo, Monaco, Consolas, 'Liberation Mono', 'Courier New', monospace"

[Params.thumbnail]
  visibility = ["list"]

[Params.sidebar]
  home = "right"
  list = "left"
  single = false
  widgets = ["search", "recent", "categories", "taglist", "social"]

[Params.widgets]
  tags_counter = true
  categories_counter = true
  recent_num = 10

[Params.widgets.social]
  facebook = "hideki.inoue"
  github = "lhideki"
  email = "hideki@inoue-kobo.com"

[[Params.widgets.social.custom]]
  title = "Qiita"
  url = "https://qiita.com/hideki"
